namespace: elastic-system

resources:
  - ./eck-namespace.yaml

helmCharts:
  - name: eck-operator
    includeCRDs: true
    repo: https://helm.elastic.co
    releaseName: eck-operator
    version: 2.6.1
    namespace: elastic-system
  - name: eck-elasticsearch
    version: 0.2.0
    namespace: elastic-system
    releaseName: elasticsearch
    valuesFile: elasticsearch-values.yaml
  - name: eck-kibana
    version: 0.2.0
    namespace: elastic-system
    releaseName: kibana
    valuesFile: kibana-values.yaml
