namespace: kube-system


helmCharts:
  - name: cilium
    includeCRDs: true
    repo: https://helm.cilium.io/
    releaseName: cilium
    version: 1.14.5
    namespace: kube-system
    valuesFile: values.yaml
