apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-python
  template:
    metadata:
      labels:
        app: grpc-python
        sidecar.istio.io/inject: 'true'
      annotations:
         sidecar.istio.io/rewriteAppHTTPProbers: "false"
    spec:
      containers:
        - name: grpc-python
          image: kimsehwan96/python-grpc
          imagePullPolicy: Always
          ports:
            - containerPort: 7777
              name: grpc
          resources:
            requests:
              cpu: 500m
            limits:
              cpu: 500m
          readinessProbe:
            grpc:
              port: 7777

