apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grpc-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - 'grpc.hayden.com'
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: false
    - hosts:
        - 'grpc.hayden.com'
      port:
        name: grpc
        number: 80
        protocol: GRPC
      tls:
        httpsRedirect: false
