namespace: grpc-python

resources:
  - ./namespace.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./mtls.yaml
  - ./grpc-virtualservice.yaml
  - ./grpc-gateway.yaml
  - ./envoy-filter.yaml

configMapGenerator:
  - name: grpc-python-proto-descriptor-configmap
    files:
      - ./helloworld.pb

generatorOptions:
  disableNameSuffixHash: true
