apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-test-server-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-test-server
        version: v2
      containers:
        - name: node-test-server
          image: kimsehwan96/node-server
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
