apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test-server-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-test-server-2
  template:
    metadata:
      labels:
        app: python-test-server-2
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: python-test-server
          image: kimsehwan96/python-server
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: APP_NAME
              value: "2번앱"
            - name: FORWARD_ENDPOINT
              value: "http://node-test-server-service.node-test-server.svc.cluster.local:80"
            - name: APP_PORT
              value: "5000"
          resources:
            requests:
              cpu: 500m
            limits:
              cpu: 500m
