apiVersion: v1
kind: Service
metadata:
  name: python-test-server-service-2
  labels:
    app: python-test-server-2
spec:
  type: ClusterIP
  selector:
    app: python-test-server-2
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
