{{- if .Values.gatewayAPI.enabled -}}
# Remove Capabilities.APIVersions.Has Statement
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller
{{- end}}
