namespace: kube-prometheus-stack

resources:
  - ./namespace.yaml
  - ./grafana-gateway.yaml
  - ./grafana-virtualservice.yaml
  - ./istio-metrics-aggregation.yaml

helmCharts:
  - name: kube-prometheus-stack
    version: 45.23.0
    namespace: kube-prometheus-stack
    releaseName: kube-prometheus-stack
    includeCRDs: true
    repo: https://prometheus-community.github.io/helm-charts
    valuesFile: values.yaml

# secretGenerator:
#   - name: additional-scrape-config
#     files:
#       - additional-scrape-config.yaml

# generatorOptions:
#   disableNameSuffixHash: true
