repoURL: https://github.com/kimsehwan96/istio-example.git

apps:
  - name: apps
    namespace: argocd
    path: apps
    targetRevision: master
  - name: argocd
    namespace: argocd
    path: argocd
    targetRevision: master
  - name: istiod
    namespace: istio-system
    path: istiod
    targetRevision: master
  - name: istio-ingress-gateway
    namespace: istio-ingress
    path: istio-ingress-gateway
    targetRevision: master
  - name: keycloak
    namespace: keycloak
    path: keycloak
    targetRevision: master
  - name: kiali
    namespace: kiali
    path: kiali
    targetRevision: master
  - name: node-test-server
    namespace: node-test-server
    path: node-test-server
    targetRevision: master
  - name: kube-prometheus-stack
    namespace: kube-prometheus-stack
    path: kube-prometheus-stack
    targetRevision: master
