repoURL: https://github.com/kimsehwan96/istio-example.git

apps:
  - name: apps
    namespace: argocd
    path: apps
    targetRevision: master
  - name: argocd
    namespace: argocd
    path: argocd
    targetRevision: master
  - name: istiod
    namespace: istio-system
    path: istiod
    targetRevision: master
  - name: istio-ingress-gateway
    namespace: istio-ingress
    path: istio-ingress-gateway
    targetRevision: master
  - name: keycloak
    namespace: keycloak
    path: keycloak
    targetRevision: master
