namespace: istio-system

resources:
  - ./istio-ingress-namespace.yaml
helmCharts:
  - name: gateway
    includeCRDs: true
    repo: https://istio-release.storage.googleapis.com/charts
    releaseName: istio-ingressgateway
    version: 1.19.0
    namespace: istio-system
